INSERT INTO lyricstable (lyrics_id, lyrics_no, lyrics_song, lyrics_status, lyrics_files) VALUES
			('101', '1', 'Fireworks', 'Completed', 'songlyrics1.pdf'),
			('102', '2', 'How You Like That', 'Completed', 'songlyrics2.pdf'),
			('103', '3', '白月光与朱砂痣', 'Completed', 'songlyrics3.pdf'),
			('104', '4', 'Vibez', 'Completed', 'songlyrics4.pdf'),
			('105', '5', 'River Flows In You', 'Completed', 'songlyrics5.pdf'),
			('106', '6', 'Photograph', 'Completed', 'songlyrics6.pdf'),
			('107', '7', 'Love Story', 'Completed', 'songlyrics7.pdf'),
			('108', '8', 'Negaraku', 'Completed', 'songlyrics8.pdf'),
			('109', '9', 'Kimi Ni Todoke', 'Completed', 'songlyrics9.pdf'),
			('110', '10', 'Where You Are', 'Completed', 'songlyrics10.pdf'),
			('111', '11', 'Everything is Alright', 'Completed', 'songlyrics11.pdf'),	
			('112', '12', 'Something There', 'Completed', 'songlyrics12.pdf'),
			('113', '13', 'One Thousand Years Later', 'Completed', 'songlyrics13.pdf'),
			('114', '14', 'As a Light Smoke', 'Completed', 'songlyrics14.pdf'),
			('115', '15', 'Amazing Grace', 'Completed', 'songlyrics15.pdf');