INSERT INTO lyricstable (lyrics_id, lyrics_no, lyrics_song, lyrics_artist, lyrics_status, lyrics_files) VALUES
			('101', '1', 'Fireworks', 'DAOKO × Kenshi Yonezu',  'Completed', 'songlyrics1.pdf'),
			('102', '2', 'How You Like That', 'Blackpink', 'Completed', 'songlyrics2.pdf'),
			('103', '3', '白月光与朱砂痣', '大籽', 'Completed', 'songlyrics3.pdf'),
			('104', '4', 'Vibez', 'Zayn Malik', 'Completed', 'songlyrics4.pdf'),
			('105', '5', 'River Flows In You', 'Yiruma', 'Completed', 'songlyrics5.pdf'),
			('106', '6', 'Photograph', 'Ed Sheeran', 'Completed', 'songlyrics6.pdf'),
			('107', '7', 'Love Story', 'Taylor Swift', 'Completed', 'songlyrics7.pdf'),
			('108', '8', 'Negaraku', 'Pierre-Jean de Beranger', 'Completed', 'songlyrics8.pdf'),
			('109', '9', 'Kimi Ni Todoke', 'Tanizawa Tomofumi', 'Completed', 'songlyrics9.pdf'),
			('110', '10', 'Where You Are', 'Disney Music Vevo', 'Completed', 'songlyrics10.pdf'),
			('111', '11', 'Everything is Alright', 'Laura Shigihara', 'Completed', 'songlyrics11.pdf'),	
			('112', '12', 'Something There', 'Disney Music Vevo', 'Completed', 'songlyrics12.pdf'),
			('113', '13', 'One Thousand Years Later', 'Wayne Lin Jun Jie', 'Completed', 'songlyrics13.pdf'),
			('114', '14', 'As a Light Smoke', 'IRiS (Tomo)', 'Completed', 'songlyrics14.pdf'),
			('115', '15', 'Amazing Grace', 'John Newton', 'Completed', 'songlyrics15.pdf');